
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:8090/category
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
app-description:
  name: stock Service
  description: stock Service
  version: 1.0
  contact:
    name: "Category Service"
    url: "http://localhost:8080/category"
springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    path: /category/swagger-ui.html
    enabled: true
