
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:8090/category
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

appDescription: "Stock API"
appVersion: "1.0.0"