
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:8090/stock
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

app-description: "stock service"
app-version: "1.0.0"
app-security-key: "authentication service for user management and authentication"


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /category/swagger-ui.html
    enabled: true
